import json
import sys

import requests

from .quizlet_set import QuizletSet


def get_lazy_dict(text):
    """
    Quizlet lazy loads page content by including a large piece of JSON in its
    response. This parses it into a dictionary.
    """
    begin_query = 'setPageData = '
    end_query = 'QLoad(\'Quizlet.setPageData\')'

    begin_index = text.find(begin_query) + len(begin_query)
    end_index = text.find(end_query) - 2
    # print(f'{begin_index}, {end_index}')
    return json.loads(text[begin_index:end_index])


def get_terms(text):
    data = get_lazy_dict(text)
    terms = []
    for term in data['termIdToTermsMap'].values():
        terms.append({
            'word': term['word'],
            'def': term['definition'],
            'imageUrl': term['_imageUrl']
        })
    return terms


def get_set(url):
    page = requests.get(url)

    terms = get_terms(page.text)
    description = 'Autogenerated by Quizhoot. Original Quizlet: {}'.format(url)
    return QuizletSet(terms, description=description)


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print('Expected path to JSON file')
    else:
        with open(sys.argv[1]) as f:
            data = json.load(f)
        url = data['url']
        out_path = data['outPath']

        qset = get_set(url)
        qset.write_terms_json(out_path)
